"""add rate limit state

Revision ID: 083447b7ee42
Revises: 74d904406d86
Create Date: 2026-09-21 12:12:24.723557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083447b7ee42'
down_revision: Union[str, Sequence[str], None] = '74d904406d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_key', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('window_start', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_key', 'scope', 'window_start', name='uq_rate_limit_state_window')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limit_state')
    # ### end Alembic commands ###
