"use client";

import { useEffect, useState } from "react";
import { connectWallet, getPublicConfig, policyOf, setPolicy, setRecipient, setWalletPaused, type Policy, type PublicConfig } from "../lib/botchain";
import { Card, Divider, Icon, Label, MBtn, Mono, Row, Spinner, fadeUp } from "../shared";
import { motion } from "framer-motion";

export default function LivePolicyView() {
  const [config, setConfig] = useState<PublicConfig | null>(null);
  const [wallet, setWallet] = useState(""); const [policy, setPolicyState] = useState<Policy | null>(null);
  const [perTx, setPerTx] = useState("0.02"); const [daily, setDaily] = useState("0.10"); const [recipient, setRecipientInput] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [transaction, setTransaction] = useState("");
  useEffect(() => { getPublicConfig().then(setConfig).catch((e: Error) => setError(e.message)); }, []);
  async function refresh(account: string) { setPolicyState(await policyOf(account)); }
  async function connect() { if (!config) return; setBusy(true); setError(""); try { const account = await connectWallet(config); setWallet(account); await refresh(account); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  async function savePolicy() { if (!config || !wallet) return; setBusy(true); setError(""); try { const expires = Math.floor(Date.now() / 1000) + 30 * 24 * 60 * 60; setTransaction(await setPolicy(config, perTx, daily, expires, true)); await refresh(wallet); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  async function updateRecipient(allowed: boolean, target = recipient) { if (!config || !wallet || !target) return; setBusy(true); setError(""); try { setTransaction(await setRecipient(config, target, allowed)); setRecipientInput(""); await refresh(wallet); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  async function togglePause() { if (!config || !wallet || !policy) return; setBusy(true); setError(""); try { setTransaction(await setWalletPaused(config, !policy.paused)); await refresh(wallet); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  return <motion.div {...fadeUp}><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-400">On-chain controls</p><h1 className="mt-2 text-3xl font-semibold">Safety policy</h1><p className="mt-2 text-sm text-slate-500">Every change opens your wallet; AgentGuard cannot sign for you.</p></div>{error && <p className="mb-4 rounded-lg border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-300">{error}</p>}<div className="grid gap-6 lg:grid-cols-[1fr_310px]"><Card className="p-6"><MBtn onClick={connect} disabled={!config || busy} className="w-full">{busy ? <><Spinner />Working…</> : <><Icon name="wallet" />{wallet ? "Reconnect wallet" : "Connect MetaMask"}</>}</MBtn><Divider /><div className="grid gap-4 sm:grid-cols-2"><div><Label>Per-transaction limit</Label><input value={perTx} onChange={(e) => setPerTx(e.target.value)} className="input mono" inputMode="decimal" /></div><div><Label>Daily limit</Label><input value={daily} onChange={(e) => setDaily(e.target.value)} className="input mono" inputMode="decimal" /></div></div><MBtn onClick={savePolicy} disabled={!wallet || busy} className="mt-5 w-full">Write policy to BOT Testnet</MBtn><Divider /><Label>Recipient allowlist</Label><div className="space-y-2">{policy?.allowed_recipients.map((address) => <div key={address} className="flex items-center justify-between rounded-lg bg-white/[.04] px-3 py-2 text-xs"><Mono>{address}</Mono><button className="text-rose-300" onClick={() => { updateRecipient(false, address); }}>Remove</button></div>)}</div><div className="mt-3 flex gap-2"><input value={recipient} onChange={(e) => setRecipientInput(e.target.value)} className="input mono" placeholder="0x recipient address" /><MBtn variant="secondary" onClick={() => updateRecipient(true)} disabled={!wallet || busy || !recipient}>Add</MBtn></div><Divider /><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold">Wallet pause</h3><p className="text-xs text-slate-500">Immediately blocks this wallet’s payments.</p></div><MBtn variant={policy?.paused ? "approve" : "danger"} onClick={togglePause} disabled={!policy || busy}>{policy?.paused ? "Unpause" : "Pause"}</MBtn></div></Card><Card className="h-fit p-5"><h2 className="text-lg font-semibold">Live contract</h2><Divider /><Row label="Wallet" value={<Mono>{wallet || "—"}</Mono>} /><Row label="Contract" value={<Mono>{config?.contract_address || "Loading…"}</Mono>} /><Row label="Network" value="BOT Testnet · 968" />{policy && <><Row label="Policy status" value={policy.paused ? "Paused" : "Active"} /><Row label="Expiry" value={policy.expires_at ? new Date(policy.expires_at).toLocaleDateString() : "—"} /></>}{transaction && config && <a className="mt-4 block text-xs text-indigo-300 underline" target="_blank" rel="noreferrer" href={config.explorer_url + "/tx/" + transaction}>View submitted transaction</a>}</Card></div></motion.div>;
}
function message(reason: unknown) { return reason instanceof Error ? reason.message : "Wallet transaction failed"; }
